export const INDICES_URL = "http://localhost:8080/nse/get_indices";

export const GET_ALL_DATA = "http://localhost:8080/nse/get_multiple_quote_info?companyNames=ACC,ADANIENT,ADANIPORTS,ADANIPOWER,AMARAJABAT,AMBUJACEM,APOLLOTYRE,ASHOKLEY,ASIANPAINT,AXISBANK,BAJFINANCE,BAJAJFINSV,BANKBARODA,BANKINDIA,BATAINDIA,BEML,BERGEPAINT,BEL,BPCL,BHARTIARTL,BHEL,BIOCON,BOSCHLTD,BRITANNIA,CESC,CIPLA,COALINDIA,DABUR,DISHTV,EXIDEIND,FEDERALBNK,GAIL,HDFCBANK,HDFC,HINDPETRO,HINDUNILVR,HINDZINC,ICICIBANK,ICICIPRULI,IDBI,IDEA,IDFC,IFCI,IBULHSGFIN,INDIANB,IOC,IGL,INDUSINDBK,INFIBEAM,INFY,INDIGO,IRB,ITC,JISLJALEQS,JPASSOCIAT,JETAIRWAYS,JINDALSTEL,PCJEWELLER,PETRONET,PIDILITIND,PFC,POWERGRID,PNB,PVR,RAYMOND,RBLBANK,RELIANCE,SAIL,STAR,SUNTV,TATACHEM,TATACOMM,TCS,TATAELXSI,TATAMTRDVR,TATAMOTORS,TATAPOWER,TATASTEEL,TECHM,TITAN,TVSMOTOR,UJJIVAN,ULTRACEMCO,UNIONBANK,UPL,VGUARD,VOLTAS,WIPRO,YESBANK,ZEEL";

export const GET_STOCK_DATA = "http://localhost:8080/nse/get_quote_info?companyName="
export const GET_INTRA_DAY_DATA = "http://localhost:8080/nse/get_intra_day_data?companyName="
